name: Excuse Bot

on:
  schedule:
    - cron: '20 22 * * 1-5'
  workflow_dispatch:

jobs:
  run-excuse-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: node excuse.js
