name: Excuse Bot

on:
 repository_dispatch:
    types: [run-excuse-bot]
 workflow_dispatch:

jobs:
  run-excuse-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: node excuse.js
